### PR TITLE
Add fill-or-kill (FOK) BinanceTimeInForce

### PR DESCRIPTION
**Pull request by elsehow**
Adds FOK BinanceTimeInForce, documented in [the official REST API](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md) and implemented in the [Python client](https://github.com/sammchardy/python-binance/blob/master/binance/enums.py#L43).

### CODE REVIEW

**Comment by elsehow** [comment]
Thank you for merging this! Do you have any specific plans to release a 1.0.7 on Maven soon? (I need a FoK feature for my project).

Thanks for your work on this excellent library.

**Comment by wcrbrm** [comment]
yes, 1.0.7 will be packaged and published on maven this week.
thanks for your contribution!

**Comment by elsehow** [comment]
Hey - any updates on 1.0.7 (sorry for being annoying)?

Happy new year.

**Comment by wcrbrm** [comment]
no problem, 1.0.7 is already visible as dependency
have happy holidays too!

**Pull request merged**
